/**
 * @File Name          : TriggerDispatcher_Test.cls
 * @Description        : 
 * @Author             : Thomas Wilkins
 * @Group              : 
 * @Last Modified By   : Thomas Wilkins
 * @Last Modified On   : 3/2/2020, 3:34:59 PM
 * @Modification Log   : 
 * Ver       Date            Author      		    Modification
 * 1.0    3/2/2020   Thomas Wilkins     Initial Version
**/
@IsTest
public class TriggerDispatcher_Test {
    
}
