/**
 * @File Name          : TriggerDispatcherException.cls
 * @Description        : Exception thrown from trigger disaptcher issues
 * @Author             : Thomas Wilkins
 * @Group              : 
 * @Last Modified By   : Thomas Wilkins
 * @Last Modified On   : 3/2/2020, 5:39:44 PM
 * @Modification Log   : 
 * Ver       Date            Author      		    Modification
 * 1.0    2/28/2020   Thomas Wilkins     Initial Version
**/
public inherited sharing class TriggerDispatcherException extends Exception {}
