/**
 * @File Name          : TriggerContextMock.cls
 * @Description        : 
 * @Author             : Thomas Wilkins
 * @Group              : 
 * @Last Modified By   : Thomas Wilkins
 * @Last Modified On   : 2/28/2020, 3:45:21 PM
 * @Modification Log   : 
 * Ver       Date            Author      		    Modification
 * 1.0    2/28/2020   Thomas Wilkins     Initial Version
**/
@IsTest
public class TriggerContextMocks {
    public class BeforeInsertMock {

    }

    public class BeforeUpdateMock {

    }

    public class BeforeDeleteMock {

    }

    public class AfterInsertMock {

    }

    public class AfterUpdateMock {

    }

    public class AfterDeleteMock {

    }

    public class AfterUndeleteMock {
        
    }
}
